services:
  tunnel:
    container_name: tunnel_one
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    networks:
      - proxy
networks:
  proxy:
    external: true
