services:
  nginx:
    image: docker.io/library/nginx:1.28.0-alpine
    container_name: blog-nginx
    volumes:
      - ./config/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./data:/usr/share/nginx/html:ro
    labels:
      - traefik.enable=true
      - traefik.http.services.blog-nginx.loadbalancer.server.port=80
      - traefik.http.routers.blog-nginx.entrypoints=websecure
      - traefik.http.routers.blog-nginx.rule=Host(`internal.example.org`)||Host(`example.org`)
      - traefik.http.routers.blog-nginx.tls=true
      - traefik.http.routers.blog-nginx.tls.certresolver=cloudflare
      - traefik.http.routers.blog-nginx.service=blog-nginx
    networks:
      - proxy
    restart: unless-stopped

networks:
  proxy:
    external: true
